#version: '3.1'
#네트웍 브릿지 추가 함

services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - was1
      - was2
    networks:
      - my_bridge_network

  was1:
    image: masungil/devops_step0
    networks:
      - my_bridge_network

  was2:
    image: masungil/devops_step0
    networks:
      - my_bridge_network

networks:
  my_bridge_network:
    driver: bridge