name: CI/CD Docker image

# 트리거를 수행할 브랜치를 지정합니다.
on:
  push:
    branches: [ main ]

jobs:
  # Spring Boot 애플리케이션을 빌드하여 도커허브에 푸시하는 과정
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    # 1. Java 17 세팅
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    # 2. Spring Boot 애플리케이션 빌드
    - name: Build with Gradle
      run: |
        chmod +x ./gradlew
        ./gradlew bootJar

    # 3. Docker 이미지 빌드
    - name: docker image build
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/devops_step0 .

    # 4. DockerHub 로그인
    - name: docker login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    # 5. Docker Hub 이미지 푸시
    - name: docker Hub push
      run: docker push ${{ secrets.DOCKER_USERNAME }}/devops_step0:latest

  deploy:
    needs: build  # build 후에 실행되도록 정의
    name: Deploy
    runs-on: [ self-hosted, label-go ] # AWS ./configure에서 사용할 label명
    steps:
    - name: docker login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    # 8080 -> 8090 포트로 수행하도록 지정
    - name: Docker run
      run: |
        sudo docker stop devops_step0 && 
        sudo docker rm devops_step0 && 
        sudo docker rmi ${{ secrets.DOCKER_USERNAME }}/devops_step0:latest
        
        sudo docker run -d -p 8090:8090 --name devops_step0 --restart always ${{ secrets.DOCKER_USERNAME }}/devops_step0:latest